// lib/constants.ts

export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  GUIDE = 'GUIDE',
  ARTISAN = 'ARTISAN',
  TRAVELER = 'TRAVELER'
}

export enum Category {
  NATURE = 'NATURE',
  CULTURE = 'CULTURE',
  ADVENTURE = 'ADVENTURE',
  HERITAGE = 'HERITAGE',
  WELLNESS = 'WELLNESS',
  COMMUNITY = 'COMMUNITY',
  ECO_VILLAGE = 'ECO_VILLAGE',
  TREKKING = 'TREKKING',
  WILDLIFE = 'WILDLIFE'
}

export enum Difficulty {
  EASY = 'EASY',
  MODERATE = 'MODERATE',
  HARD = 'HARD',
  CHALLENGING = 'CHALLENGING',
  EXPERT = 'EXPERT'
}

export enum ProductCategory {
  CRAFTS = 'CRAFTS',
  ORGANIC_FOOD = 'ORGANIC_FOOD',
  HANDLOOM = 'HANDLOOM',
  WELLNESS = 'WELLNESS',
  FASHION = 'FASHION',
  ACCESSORIES = 'ACCESSORIES',
  HOME_DECOR = 'HOME_DECOR',
  FOOD = 'FOOD',
  CLOTHING = 'CLOTHING'
}

export enum OrderStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED'
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED'
}
