package com.ecoculture.config;

import com.ecoculture.model.Destination;
import com.ecoculture.model.Product;
import java.util.Arrays;
import java.util.List;

public class SeedData {

    public static List<Destination> getDestinations() {
        return Arrays.asList(
            Destination.builder()
                .name("Munnar Eco Village").slug("munnar-eco-village").category(Destination.Category.COMMUNITY)
                .country("India").region("Kerala").latitude(10.0889).longitude(77.0595)
                .sustainabilityScore(95).carbonSaved(2.4).avgCost(3800).difficulty(Destination.Difficulty.EASY).featured(true)
                .bestSeason("October to March")
                .shortDescription("Solar-powered village nestled in Kerala's misty tea highlands")
                .description("Perched at 1,600 metres in the Western Ghats, Munnar Eco Village is a living model of sustainable tourism. The entire settlement runs on solar power generated by rooftop panels, while rainwater harvesting systems supply 100% of daily water needs. Guests stay in handcrafted cottages built using locally sourced bamboo, mud, and laterite stone — materials that keep interiors cool without air-conditioning. Morning walks through shade-grown organic tea gardens are guided by third-generation tea farmers who explain the entire tea-making process. Ayurvedic wellness sessions using plants grown on-site complete the immersive experience. The village directly employs 47 local families and donates 12% of all revenue to the Munnar Tribal Education Fund.")
                .highlights("[\"Solar-powered facilities — zero grid dependency\", \"Organic tea plantation walks with master farmers\", \"Traditional Ayurvedic treatments on-site\", \"Bamboo and mud cottage accommodation\", \"Rainwater harvesting — 100% water self-sufficient\", \"Supports 47 local tribal families directly\"]")
                .imageUrl("https://picsum.photos/seed/munnar-eco-village-hero/1200/800")
                .galleryUrls("[\"https://picsum.photos/seed/munnar-gallery-tea/800/600\", \"https://picsum.photos/seed/munnar-gallery-cottage/800/600\", \"https://picsum.photos/seed/munnar-gallery-mist/800/600\", \"https://picsum.photos/seed/munnar-gallery-sunrise/800/600\", \"https://picsum.photos/seed/munnar-gallery-ayurveda/800/600\"]")
                .build(),
            Destination.builder()
                .name("Auroville Eco Township").slug("auroville-eco-township").category(Destination.Category.COMMUNITY)
                .country("India").region("Tamil Nadu").latitude(12.0059).longitude(79.8107)
                .sustainabilityScore(97).carbonSaved(4.2).avgCost(2800).difficulty(Destination.Difficulty.EASY).featured(true)
                .bestSeason("November to February")
                .shortDescription("India's most ambitious experiment in conscious and sustainable community living")
                .description("Founded in 1968 on the vision of human unity, Auroville spans 20 square kilometres near Pondicherry and is home to 3,500 residents from over 50 countries. The township has planted more than 3 million trees on what was once barren land, creating one of the most remarkable reforestation stories in India. Visitors can tour the Matrimandir — a golden geodesic meditation dome at the township's spiritual heart — explore working renewable energy installations, and participate in organic farming workshops. The township generates a significant portion of its electricity through wind and solar systems. Artisan workshops producing handmade paper, natural textiles, and organic food products welcome visitors and offer immersive craft sessions. Guest houses across the township follow strict ecological building norms.")
                .highlights("[\"Matrimandir — iconic golden meditation dome\", \"3 million trees planted on reclaimed land\", \"Wind and solar renewable energy systems\", \"50+ artisan workshops open to visitors\", \"Organic farming and permaculture tours\", \"Residents from 50+ countries — global village\"]")
                .imageUrl("https://picsum.photos/seed/auroville-township-hero/1200/800")
                .galleryUrls("[\"https://picsum.photos/seed/auroville-matrimandir/800/600\", \"https://picsum.photos/seed/auroville-forest/800/600\", \"https://picsum.photos/seed/auroville-workshop/800/600\", \"https://picsum.photos/seed/auroville-solar/800/600\"]")
                .build(),
            Destination.builder()
                .name("Khonoma Green Village").slug("khonoma-green-village").category(Destination.Category.COMMUNITY)
                .country("India").region("Nagaland").latitude(25.6518).longitude(94.0318)
                .sustainabilityScore(92).carbonSaved(3.1).avgCost(2200).difficulty(Destination.Difficulty.MODERATE).featured(false)
                .bestSeason("October to April")
                .shortDescription("Asia's first green village — home to the legendary Angami Naga warriors")
                .description("Khonoma, 20 km west of Kohima, is widely recognised as Asia's first green village. The Angami Naga community here voluntarily declared their surrounding forests a wildlife sanctuary in 1998, banning all hunting and logging. The result is a thriving biodiversity hotspot where over 200 bird species have been recorded. Village homestays are entirely community-run, with guests sleeping in traditional Naga longhouses built from wood and bamboo without a single nail. Meals feature exclusively foraged and farm-grown food. The community also maintains terraced rice cultivation using 700-year-old irrigation systems still in active use today. Every rupee spent flows directly into the village council's community development fund.")
                .highlights("[\"Asia's first declared green village\", \"Self-imposed wildlife sanctuary since 1998\", \"200+ bird species — birdwatcher's paradise\", \"700-year-old terraced rice irrigation systems\", \"Traditional Naga longhouse homestays\", \"100% community-run, zero outside ownership\"]")
                .imageUrl("https://picsum.photos/seed/khonoma-nagaland-hero/1200/800")
                .galleryUrls("[\"https://picsum.photos/seed/khonoma-longhouse/800/600\", \"https://picsum.photos/seed/khonoma-terrace/800/600\", \"https://picsum.photos/seed/khonoma-forest/800/600\"]")
                .build()
            // ... truncated for brevitiy in this step, I will add more in next chunks
        );
    }
}
